apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: my-template
spec:
  path: ./template.yaml
  type: service
  steps:
    - id: fetch
      name: Fetch
      action: fetch:template
    # Add other steps as needed