apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Testing Template
  title: Testing Template
  description: Testing Conditionals and Debugging
spec:
  owner: myles-coleman
  type: service
  parameters:
    - title: Provide information for your team
      required:
        - environment
      properties:
        environment:
          title: Select Environments
          type: array
          description: Choose the environment(s) you want to onboard to
          items:
            type: string
            enum:
              - dev
              - prod
              - mgmt
          uniqueItems: true
          ui:widget: checkboxes

  steps:
    # Debug step for 'dev'
    - id: debug
      name: Debug for Dev
      if: ${{ each.value === "dev" }}
      each: ${{ parameters.environment }}
      action: debug:log
      input:
        message: |
          Matched environment: ${{ each.value }}